### ISSUE TITLE
NoSuchMethodError: android.view.ViewTreeObserver.removeOnGlobalLayoutListener

### ISSUE THREAD

**Issue by marczych** [iFixit/iFixitAndroid#224]
We have several crash reports for this:

```java
java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeOnGlobalLayoutListener
at com.dozuki.ifixit.ui.guide.view.GuideIntroViewFragment$4.onGlobalLayout(GuideIntroViewFragment.java:148)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:566)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1598)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2581)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4697)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
at dalvik.system.NativeStart.main(Native Method)
```

Solution is here: http://stackoverflow.com/a/15162928/1135611

**Comment by timothyasp** [comment]
Looks like this was fixed in #227
