### ISSUE TITLE
Crash on choosing step to edit

### ISSUE THREAD

**Issue by addison-grant** [iFixit/iFixitAndroid#268]
aI was only able to get this to happen with a specific teardown.

Pixel, Android 7.1.1

Got the app to crash by
1. being logged in as Kyle
2. going to My Guides
3. choosing iPhone 7 Plus Teardown
4. clicking on Step 6 (or any step I think).
5. breakage

Have not been able to reproduce with other guides/teardowns

Log (this error kept repeating in a seemingly infinite loop):
```
03-22 10:32:12.700  1115  2954 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 888312)
03-22 10:32:12.701  1115  2954 W ActivityManager: Exception in new application when starting activity com.dozuki.ifixit/.ui.guide.create.StepEditActivity
03-22 10:32:12.701  1115  2954 W ActivityManager: android.os.TransactionTooLargeException: data parcel size 888312 bytes
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:884)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1309)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:866)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6608)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6672)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2795)
03-22 10:32:12.701  1115  2954 W ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
03-22 10:32:12.701  1115  2954 E ActivityManager: Exception thrown launching activities in ProcessRecord{ef8eb17 8000:com.dozuki.ifixit/u0a136}
03-22 10:32:12.701  1115  2954 E ActivityManager: android.os.TransactionTooLargeException: data parcel size 888312 bytes
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:884)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1309)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:866)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6608)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6672)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2795)
03-22 10:32:12.701  1115  2954 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
03-22 10:32:12.702  1115  2954 I ActivityManager: Killing 8000:com.dozuki.ifixit/u0a136 (adj 0): error during init
03-22 10:32:12.702  1115  2954 D ActivityManager: cleanUpApplicationRecord -- 8000
03-22 10:32:12.711  1115  2954 I ActivityManager: Start proc 8026:com.dozuki.ifixit/u0a136 for activity com.dozuki.ifixit/.ui.guide.create.StepEditActivity
03-22 10:32:12.714  8026  8026 I art     : Late-enabling -Xcheck:jni
03-22 10:32:12.737  1115  2955 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 888312)
03-22 10:32:12.738  1115  2955 W ActivityManager: Exception in new application when starting activity com.dozuki.ifixit/.ui.guide.create.StepEditActivity
03-22 10:32:12.738  1115  2955 W ActivityManager: android.os.TransactionTooLargeException: data parcel size 888312 bytes
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:884)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1309)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:866)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6608)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6672)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2795)
03-22 10:32:12.738  1115  2955 W ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
03-22 10:32:12.738  1115  2955 E ActivityManager: Exception thrown launching activities in ProcessRecord{3e24322 8026:com.dozuki.ifixit/u0a136}
03-22 10:32:12.738  1115  2955 E ActivityManager: android.os.TransactionTooLargeException: data parcel size 888312 bytes
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:884)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1309)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:866)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6608)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6672)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2795)
03-22 10:32:12.738  1115  2955 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
03-22 10:32:12.738  1115  2955 I ActivityManager: Killing 8026:com.dozuki.ifixit/u0a136 (adj 0): error during init
03-22 10:32:12.738  1115  2955 D ActivityManager: cleanUpApplicationRecord -- 8026
03-22 10:32:12.750  1115  2955 I ActivityManager: Start proc 8040:com.dozuki.ifixit/u0a136 for activity com.dozuki.ifixit/.ui.guide.create.StepEditActivity
03-22 10:32:12.755  8040  8040 I art     : Late-enabling -Xcheck:jni
```

Normal log when going into step edit:
```
03-22 10:39:37.838  1115  1484 I nanohub : osLog: bridge: Got event 0x00000221 with 1296 bytes of data
03-22 10:39:37.846  1115  1484 I nanohub : osLog: bridge: Got event 0x00000221 with 592 bytes of data
03-22 10:39:37.850  1115  1484 I nanohub : osLog: bridge: Issuing on-demand request for Cell Info
03-22 10:39:37.874  1115  1484 I nanohub : osLog: bridge: Got event 0x00000225 with 456 bytes of data
03-22 10:39:37.887  1115  1484 I nanohub : osLog: [WifiLocator] incoming scan 0x20028c40
03-22 10:39:37.888  1115  1484 I nanohub : osLog: [WifiLocator] wifi position success (20m)
03-22 10:39:37.890  1115  1484 I nanohub : osLog: [CellLocator] incoming scan 0x20028b5c
03-22 10:39:37.891  1115  1484 I nanohub : osLog: [CellLocator] cell position failure
03-22 10:39:37.893  1115  1484 I nanohub : osLog: [LocEng] Sending Scan Request with interval ~60 seconds, ~187 meters
03-22 10:39:37.894  1115  1484 I nanohub : osLog: [GeofencingEngine] LocationCallback: provider 1, accuracy 20 meters, 0 transitions
03-22 10:39:38.110  5618  5644 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@d7bbac7 HexData = [010000000404000011000000514f454d484f4f4bfa0308000100000000]
03-22 10:39:38.110  5618  5644 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0
03-22 10:39:38.110  5618  5644 D QcrilMsgTunnelSocket: Response ID 525306 is not served in this process.
03-22 10:39:38.110  5618  5644 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps
03-22 10:39:38.111  5618  5618 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
03-22 10:39:38.113  1753  1753 D QC_RIL_OEM_HOOK: Received Broadcast Intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
03-22 10:39:38.113  1753  1753 D QC_RIL_OEM_HOOK: Oem ID in QCRILHOOK UNSOL RESP is QOEMHOOK
03-22 10:39:38.790  1115 13475 I ActivityManager: START u0 {cmp=com.dozuki.ifixit/.ui.guide.create.StepsActivity (has extras)} from uid 10136 on display 0
03-22 10:39:38.840 29034 29034 W ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
03-22 10:39:38.845 29034 29082 I Api     : Performing API call: GET https://tasp.cominor.com/api/2.0/guides/67385?unpatrolled&excludePrerequisiteSteps
03-22 10:39:38.845 29034 29082 I Api     : Request body: null
03-22 10:39:38.968  1115  1153 I ActivityManager: Displayed com.dozuki.ifixit/.ui.guide.create.StepsActivity: +166ms
03-22 10:39:39.003 29034 29061 D OpenGLRenderer: endAllActiveAnimators on 0x79fffe4800 (RippleDrawable) with handle 0x7a009186e0
03-22 10:39:39.420 29034 29082 D Api     : Response code: 200
03-22 10:39:39.423 29034 29082 D Api     : Response body: {"conclusion_raw":"","conclusion_rendered":"","difficulty":"Moderate","documents":[],"flags":[{"title":"Featured Guide","flagid":"GUIDE_STARRED","text":"This guide has been found to be exceptionally cool by the iFixit staff."}],"guideid":67385,"image":{"id":896894,"guid":"yi16EvLLNgGtBLPQ","mini":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.mini","thumbnail":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.thumbnail","standard":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.standard","medium":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.medium","large":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.large","huge":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ.huge","original":"https:\/\/tasp.cominor.com\/igi\/yi16EvLLNgGtBLPQ"},"introduction_raw":"Our iPhone 7 Plus is still on the chopping block, but we just can't help ourselves\u2014it's time to look at Apple Watch Series 2. The Series 2 looks all-but-identical to the newly rechristened \"Series 1\"\u2014but is it the same on the inside? With added features such as built-in GPS, waterproofing, and a variety of new bands and cases, Apple's new wearable was destined for the teardown table. It's time to see if this \"ultimate device for a healthy life\" has what it takes to go the distance in terms of repairability.\n\n'''Did you miss our first look at the \"best, most advanced iPhone ever\"? Hop over to our [https:\/\/www.ifixit.com\/Teardown\/iPhone+7+Plus+Teardown\/67384|iPhone 7 Plus teardown|new_window=true] and just try to keep up!'''\n\nReady to dive in?  Keep pace with the latest news from the repair world by following us on [https:\/\/www.facebook.com\/iFixit|Facebook|new_window=true], [http:\/\/instagram.com\/ifixit|Instagram|new_window=true], or [https:\/\/twitter.com\/ifixit|Twitter|new_window=true].\n\n[video|https:\/\/www.youtube.com\/watch?v=yAE3Q5adDWA]","introduction_rendered":"<p>Our iPhone 7 Plus is still on the chopping block, but we just can't help ourselves\u2014it's time to look at Apple Watch Series 2. The Series 2 looks all-but-identical to the newly rechristened &quot;Series 1&quot;\u2014but is it the same on the inside? With added features such as built-in GPS, waterproofing, and a variety of new bands and cases, Apple's new wearable was destined for the teardown table. It's time to see if this &quot;ultimate device for a healthy life&quot; has what it takes to go the distance in terms of repairability.<\/p>\n\n<p><strong>Did you miss our first look at the &quot;best, most advanced iPhone ever&quot;? Hop over to our <a href=\"https:\/\/tasp.cominor.com\/Teardown\/iPhone+7+Plus+Teardown\/67384\" target=\"_blank\">iPhone 7 Plus teardown<\/a> and just try to keep up!<\/strong><\/p>\n\n<p>Ready to dive in?  Keep pace with the latest news from the repair world by following us on <a href=\"https:\/\/www.facebook.com\/iFixit\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">Facebook<\/a>, <a href=\"http:\/\/instagram.com\/ifixit\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">Instagram<\/a>, or <a href=\"https:\/\/twitter.com\/ifixit\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">Twitter<\/a>.<\/p>\n\n<div class=\"large videoFrame videoBox_center\" style=\"width:570px\"><div class=\"videoBox\"><iframe class=\"youtube-player\" type=\"text\/html\" src=\"https:\/\/www.youtube.com\/embed\/yAE3Q5adDWA?wmode=opaque\" width=\"560\" height=\"315\" frameborder=\"0\"><\/iframe><\/div><\/div>","locale":"en","parts":[],"prerequisites":[],"steps":[{"title":"","lines":[{"text_raw":"Our watches are getting smarter every day. Let's see what the newest generation of Apple wrist accessories has to offer:","bullet":"black","level":0,"lineid":null,"text_rendered":"Our watches are getting smarter every day. Let's see what the newest generation of Apple wrist accessories has to offer:"},{"text_raw":"Second-generation OLED Retina display with Force Touch","bullet":"red","level":1,"lineid":null,"text_rendered":"Second-generation OLED Retina display with Force Touch"},{"text_raw"
03-22 10:39:39.423 29034 29082 D Api     : Request time: 575ms
03-22 10:39:39.423 29034 29082 D Api     : Response full: Response{protocol=http/1.1, code=200, message=OK, url=https://tasp.cominor.com/api/2.0/guides/67385?unpatrolled&excludePrerequisiteSteps}
03-22 10:39:39.505 29034 29051 I GAV3    : Thread[GAThread,5,main]: No campaign data found.
03-22 10:39:39.554  2847  2052 E ctxmgr  : [AppIntervalImpl]closeInterval: ongoing
03-22 10:39:39.595  2847  3841 I PlaceInferenceEngine: [anon] Setup for configuration 105:[]
03-22 10:39:39.595  2847  3841 I PlaceInferenceEngine: [anon] Active modules after start(): 0
03-22 10:39:41.842  2193  2193 I clatd   : Detecting NAT64 prefix from DNS...
03-22 10:39:41.848  2193  2193 E clatd   : plat_prefix/dns(ipv4only.arpa) status = 7/No address associated with hostname
03-22 10:39:41.848  2193  2193 W clatd   : dns64_detection -- error, sleeping for 120 seconds
03-22 10:39:42.026  1115 13476 I ActivityManager: START u0 {cmp=com.dozuki.ifixit/.ui.guide.create.StepEditActivity (has extras)} from uid 10136 on display 0
03-22 10:39:42.086 29034 29034 W ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
03-22 10:39:42.096 29034 29060 I Api     : Performing API call: GET https://tasp.cominor.com/api/2.0/sites/info
03-22 10:39:42.096 29034 29060 I Api     : Request body: null
03-22 10:39:42.173 29034 29060 D Api     : Response code: 200
03-22 10:39:42.173 29034 29060 D Api     : Response body: {"siteid":2,"name":"ifixit","domain":"www.cominor.com","title":"iFixit","theme":"custom","color":"#666666","private":false,"description":"iFixit is a global community of people helping each other repair things. Let's fix the world, one device at a time. Troubleshoot with experts in the Answers forum\u2014and build your own how-to guides to share with the world. Fix your Apple and Android devices\u2014and buy all the parts and tools needed for your DIY repair projects.","authentication":{"standard":true,"public-registration":true},"answers":true,"collections":true,"store":"http:\/\/www.ifixit.com\/Parts-Store","priority":1,"object-name-singular":"Device","object-name-plural":"Devices","topic-name-singular":"repair","topic-name-plural":"repair","feature-mobile-scanner":false,"google-oauth2-clientid":"622418919965-qcvbv04spukbdo9ut8pevt4pucmkp86o@developer.gserviceaccount.com","guide-types":{"replacement":{"title":"%device %thing Replacement","prompt":"What part are you replacing?","name":"Replacement","description":"Most guides. How to swap out a particular component."},"disassembly":{"title":"%device Disassembly","prompt":"","name":"Disassembly","description":"Completely dismantle and remove every component. For repairs like water damage cleaning."},"teardown":{"title":"%device Teardown","prompt":"","name":"Teardown","description":"A fun, educational disassembly to get a look inside; not intended to be followed for repair."},"technique":{"title":"How to %device","prompt":"","name":"Technique","description":"Tips, tricks, or shortcuts. Explain how to do something like use a tool or calibrate a part."}},"logo":{"image":{"id":282304,"guid":"YlogWMLVAtHbPF5J","mini":"https:\/\/tasp.cominor.com\/igi\/YlogWMLVAtHbPF5J.mini","thumbnail":"https:\/\/tasp.cominor.com\/igi\/YlogWMLVAtHbPF5J.thumbnail","standard":"https:\/\/tasp.cominor.com\/igi\/YlogWMLVAtHbPF5J.standard","original":"https:\/\/tasp.cominor.com\/igi\/YlogWMLVAtHbPF5J"},"srcid":null,"width":788,"height":243,"ratio":"VARIABLE","markup":null,"exif":{"FileName":"iFixit-logo.png"}}}
03-22 10:39:42.173 29034 29060 D Api     : Request time: 77ms
03-22 10:39:42.173 29034 29060 D Api     : Response full: Response{protocol=http/1.1, code=200, message=OK, url=https://tasp.cominor.com/api/2.0/sites/info}
03-22 10:39:42.371  1115  1153 I ActivityManager: Displayed com.dozuki.ifixit/.ui.guide.create.StepEditActivity: +330ms
03-22 10:39:45.904  3201  3201 E NoOpActionFactory: Perform called on NOOp Action! created by: createDisplayMenuPopupAction
03-22 10:39:45.908  3201  3201 E NoOpActionFactory: Perform called on NOOp Action! created by: createDisplayMenuPopupAction
03-22 10:39:47.220  1115  1138 W ActivityManager: Activity stop timeout for ActivityRecord{c7b0a11 u0 com.dozuki.ifixit/.ui.topic.TopicActivity t1728}
03-22 10:39:48.624  5618  5644 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@d7bbac7 HexData = [010000000404000011000000514f454d484f4f4bfa0308000100000000]
03-22 10:39:48.624  5618  5644 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0
03-22 10:39:48.625  5618  5644 D QcrilMsgTunnelSocket: Response ID 525306 is not served in this process.
03-22 10:39:48.625  5618  5644 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps
03-22 10:39:48.628  5618  5618 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
03-22 10:39:48.656  1753  1753 D QC_RIL_OEM_HOOK: Received Broadcast Intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
03-22 10:39:48.656  1753  1753 D QC_RIL_OEM_HOOK: Oem ID in QCRILHOOK UNSOL RESP is QOEMHOOK
03-22 10:39:53.545  1115  4705 D DhcpClient: Received packet: 90:60:f1:58:96:5c ACK: your new IP /192.168.41.121, netmask /255.255.0.0, gateways [/192.168.41.2] DNS servers: /8.8.8.8 /8.8.4.4 , lease time 86400
03-22 10:39:55.600  2847  2052 I GCoreUlr: Successfully inserted 1 locations
03-22 10:39:56.922  1115  4705 D DhcpClient: Received packet: 00:23:12:0f:fc:64 ACK: your new IP /192.168.42.84, netmask /255.255.0.0, gateways [/192.168.41.2] DNS servers: /8.8.8.8 /8.8.4.4 , lease time 86400
03-22 10:40:00.614  1115  4705 D DhcpClient: Received packet: 68:5b:35:99:d3:43 ACK: your new IP /192.168.40.201, netmask /255.255.0.0, gateways [/192.168.41.2] DNS servers: /8.8.8.8 /8.8.4.4 , lease time 86400
03-22 10:40:00.655  4601  4601 W Thread-1294: type=1400 audit(0.0:19405): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_
```

From https://github.com/iFixit/iFixitAndroid/issues/266#issuecomment-288480902

**Comment by timothyasp** [comment]
Just walked through those steps, and it looks like this has been fixed.
