### ISSUE TITLE
Broken guide publishing toggle

### ISSUE THREAD

**Issue by addison-grant** [iFixit/iFixitAndroid#269]
I didn't see an existing issue for this.

Pixel, Android 7.1.1

Looks like there are some bugs around the Publishing toggle

On guide creation/edit
1. Toggle the guide (at the top of step edit) several times in a row
2. See error message popup
   - An error has occurred while trying to load content from our servers.

```

03-22 10:56:05.006 32307   833 I Api     : Performing API call: DELETE https://tasp.cominor.com/api/2.0/guides/1091621/public?revisionid=4405956
03-22 10:56:05.006 32307   833 I Api     : Request body: okhttp3.RequestBody$2@c616171
03-22 10:56:05.040 32307 32307 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-22 10:56:05.832 32307   833 D Api     : Response code: 200
03-22 10:56:05.832 32307   833 D Api     : Response body: {"conclusion_raw":"To reassemble your device, follow these instructions in reverse order.","conclusion_rendered":"<p>To reassemble your device, follow these instructions in reverse order.<\/p>","difficulty":"Moderate","documents":[],"flags":[{"title":"In Progress","flagid":"GUIDE_IN_PROGRESS","text":"This guide is a work in progress. Reload periodically to see the latest changes!"}],"guideid":1091621,"image":null,"introduction_raw":null,"introduction_rendered":"","locale":"en","parts":[],"prerequisites":[],"steps":[{"title":"","lines":[{"text_raw":"Wisdom here","bullet":"black","level":0,"lineid":null,"text_rendered":"Wisdom here"}],"guideid":1091621,"stepid":613369,"orderby":1,"revisionid":2930115,"media":{"type":"image","data":[]},"comments":[]}],"subject":"Wisdom","summary":"","time_required":"No estimate","time_required_min":0,"time_required_max":0,"title":"iPhone 8 Wisdom Replacement","tools":[],"type":"replacement","revisionid":4405957,"created_date":1490205287,"published_date":0,"modified_date":1490205365,"prereq_modified_date":0,"public":false,"comments":[],"category":"iPhone 8","url":"https:\/\/tasp.cominor.com\/Guide\/iPhone+8+Wisdom+Replacement\/1091621","patrol_threshold":500,"can_edit":true,"favorited":false,"completed":false,"author":{"userid":2,"username":"Kyle Wiens","unique_username":"kyle","join_date":null,"image":{"id":277233,"guid":"MrphvTGGRcKHXRV2","mini":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2.mini","thumbnail":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2.thumbnail","standard":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2.standard","medium":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2.medium","large":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2.large","original":"https:\/\/tasp.cominor.com\/igi\/MrphvTGGRcKHXRV2"},"reputation":16012,"url":"https:\/\/tasp.cominor.com\/User\/2\/Kyle+Wiens","teams":[1],"privileges":["Admin"]},"langid":"en","featured_documentid":null}
03-22 10:56:05.832 32307   833 D Api     : Request time: 826ms
03-22 10:56:05.832 32307   833 D Api     : Response full: Response{protocol=http/1.1, code=200, message=OK, url=https://tasp.cominor.com/api/2.0/guides/1091621/public?revisionid=4405956}
03-22 10:56:07.647 32307   850 I Api     : Performing API call: PUT https://tasp.cominor.com/api/2.0/guides/1091621/public?revisionid=4405957
03-22 10:56:07.647 32307   850 I Api     : Request body: okhttp3.RequestBody$2@8732af4
03-22 10:56:07.667 32307 32307 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19747): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19748): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19749): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19750): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19751): avc: denied { search } for name="600000.qcom,pcie" dev="sysfs" ino=17978 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_pcie:s0 tclass=dir permissive=0
03-22 10:56:07.762  3047  3047 W CL--778036960: type=1400 audit(0.0:19752): avc: denied { search } for name="600000.qcom,pcie" dev="sysfs" ino=17978 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_pcie:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19753): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19754): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19755): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19756): avc: denied { search } for name="net" dev="sysfs" ino=28048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19757): avc: denied { search } for name="600000.qcom,pcie" dev="sysfs" ino=17978 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_pcie:s0 tclass=dir permissive=0
03-22 10:56:07.979  4601  4601 W CL--729274080: type=1400 audit(0.0:19758): avc: denied { search } for name="600000.qcom,pcie" dev="sysfs" ino=17978 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_pcie:s0 tclass=dir permissive=0
03-22 10:56:08.599 32307   850 W System.err: java.io.EOFException
03-22 10:56:08.599 32307   850 W System.err: 	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
03-22 10:56:08.599 32307   850 W System.err: 	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
03-22 10:56:08.599 32307   850 W System.err: 	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.InflaterSource.refill(InflaterSource.java:101)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.InflaterSource.read(InflaterSource.java:62)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.GzipSource.read(GzipSource.java:80)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.Buffer.writeAll(Buffer.java:996)
03-22 10:56:08.599 32307   850 W System.err: 	at okio.RealBufferedSource.readString(RealBufferedSource.java:189)
03-22 10:56:08.599 32307   850 W System.err: 	at okhttp3.ResponseBody.string(ResponseBody.java:174)
03-22 10:56:08.599 32307   850 W System.err: 	at com.dozuki.ifixit.util.api.Api.getResponse(Api.java:383)
03-22 10:56:08.599 32307   850 W System.err: 	at com.dozuki.ifixit.util.api.Api.performAndParseApiCall(Api.java:325)
03-22 10:56:08.600 32307   850 W System.err: 	at com.dozuki.ifixit.util.api.Api$5.doInBackground(Api.java:294)
03-22 10:56:08.601 32307   850 W System.err: 	at com.dozuki.ifixit.util.api.Api$5.doInBackground(Api.java:291)
03-22 10:56:08.601 32307   850 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-22 10:56:08.601 32307   850 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 10:56:08.601 32307   850 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-22 10:56:08.601 32307   850 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-22 10:56:08.601 32307   850 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-22 10:56:08.601 32307   850 E Api     : API error
03-22 10:56:08.601 32307   850 E Api     : java.io.IOException: Unexpected code
03-22 10:56:08.601 32307   850 E Api     : 	at com.dozuki.ifixit.util.api.Api.getResponse(Api.java:427)
03-22 10:56:08.601 32307   850 E Api     : 	at com.dozuki.ifixit.util.api.Api.performAndParseApiCall(Api.java:325)
03-22 10:56:08.601 32307   850 E Api     : 	at com.dozuki.ifixit.util.api.Api$5.doInBackground(Api.java:294)
03-22 10:56:08.601 32307   850 E Api     : 	at com.dozuki.ifixit.util.api.Api$5.doInBackground(Api.java:291)
03-22 10:56:08.601 32307   850 E Api     : 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-22 10:56:08.601 32307   850 E Api     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 10:56:08.601 32307   850 E Api     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-22 10:56:08.601 32307   850 E Api     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-22 10:56:08.601 32307   850 E Api     : 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by timothyasp** [comment]
This was fixed with an API bugfix.
