### ISSUE TITLE
ActivityNotFoundException: No Activity found to handle Intent

### ISSUE THREAD

**Issue by eileenfan** [iFixit/iFixitAndroid#281]
//package name: com.dozuki.ifixit
//version: 2.0.1
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/Item/Philips_screwdrivers }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:824)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at com.dozuki.ifixit.ui.guide.view.PartsToolsAdapter$1.onClick(PartsToolsAdapter.java:66)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by bonebizz21** [comment]
Sip
